table databases
	lineageTag: e978aa84-469a-4d66-aee4-cdb47f4f4f24

	column LogicalServerName_s
		dataType: string
		lineageTag: b060badb-9374-42d4-91da-7d0e92809ecb
		summarizeBy: none
		sourceColumn: LogicalServerName_s

		annotation SummarizationSetBy = Automatic

	column database_name
		dataType: string
		lineageTag: 27222f27-08f6-4634-a6bc-f35eb9eb04d2
		summarizeBy: none
		sourceColumn: database_name

		annotation SummarizationSetBy = Automatic

	partition databases = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Path & "fileiostats.csv"),[Delimiter=if DelimitadorTab = true then "	" else ",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Promoted Headers",{{"TimeGenerated", type datetime}, {"database_id", Int64.Type}, {"file_id", Int64.Type}, {"num_of_reads", Int64.Type}, {"num_of_writes", Int64.Type}, {"num_of_bytes_read", Int64.Type}, {"num_of_bytes_written", Int64.Type}, {"io_stall_read_ms", Int64.Type}, {"io_stall_write_ms", Int64.Type}, {"io_stall_ms", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type3",{"LogicalServerName_s", "database_name"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

